<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Login_admin extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Admin_model');
    }

    public function index()
    {
		if($this->session->userdata('admin_logined') && $this->session->userdata('admin_logined') == true)
		{
			redirect('home2');
		}
		
		if(!$this->input->post())	
		{
			$this->load->view('Login_admin');
		}
		else
		{
			$cek_login=$this->Admin_model->ambil_cek_login(
				$this->input->post('username'),
				$this->input->post('password')
				);
			
			if(!empty($cek_login))
			{
				$this->session->set_userdata('admin_logined', true);
				$this->session->set_userdata('username',$cek_login->username);
				redirect("customer");


			}
			else 
			{
				redirect("Login_admin");
			}
		}
        
    } 
	
	public function logout()
    {
		$this->session->unset_userdata('admin_logined');
		redirect("/");
    } 
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */