<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Login extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('customer_model');
    }

    public function index()
    {
		if($this->session->userdata('customer_logined') && $this->session->userdata('customer_logined') == true)
		{
			redirect('customer2');
		}
		
		if(!$this->input->post())
		{
			$this->load->view('login');
		}
		else
		{
			$cek_login=$this->customer_model->ambil_cek_login(
				$this->input->post('id_cstmr'),
				$this->input->post('nama_cstmr')
				);
			
			if(!empty($cek_login))
			{
				$this->session->set_userdata('customer_logined', true);
				$this->session->set_userdata('id_cstmr',$cek_login->id_cstmr);
				redirect("customer2");


			}
			else 
			{
				redirect("/");
			}
		}
        
    } 
	
	public function logout()
    {
		$this->session->unset_userdata('customer_logined');
		redirect("/");
    } 
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */